apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techdocs
  description: "Documentação prática e referência tecnologica"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: Documentation
  lifecycle: production
  owner: platform
