site_name: Tech Docs
site_description: "Documentação de práticas e referencias de tecnologia CodeIA Tech"

nav:
  - Home: index.md
  - Setup: setup.md
  - Architecture: architecture.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
