site_name: Tech Docs
site_description: "Documentação de práticas e referencias de tecnologia CodeIA Tech"

nav:
  - Home: "site/home/index.md"
  - CodeIA Tech:
    - Quem somos: "site/home/quem_somos.md"
  - Architecture: "site/architecture/index.md"

theme:
  name: material

plugins:
  - techdocs-core