site_name: Tech Docs
site_description: "Documentação de práticas e referencias de tecnologia CodeIA Tech"
site_author: "Team Platform"
repo_url: https://github.com/mcianci2024/codeia-techdocs
edit_url: edit/main/docs/

nav:
  - Home: index.md
  - Setup: setup.md
  - Architecture: architecture.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
