site_name: Main Docs
site_description: "Principal Docs Apps"
site_author: "Team Platform"
repo_url: https://github.com/mcianci2024/codeia-techdocs
edit_url: edit/main/docs/
nav:
  - Home: index.md
  - Setup: setup.md
  - Architecture: architecture.md
  - Troubleshooting: troubleshooting.md
theme:
  name: material
